baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Pavithra's Portfolio"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3
  customCSS: false

  # home
  disable_home: false
  name: "Pavithra Ganesan"
  namecolor: ff0090
  profession: "Student"
  github: "https://github.com/PaviG26"
  linkedin: "https://www.linkedin.com/in/pavithra-ganesan-792b82222/"

  # About
  disable_about: false
  descripe_l1_person: "I am Pavithra G from Madurai. I am currently pursing my B.Tech in computer science at amrita school of engineering, Chennai campus.."
  descripe_l2_person: "I know languages C, C++, Python and Java. I am most comfortable with C++. I have done a couple of datascience and development projects using java and  python. I am an optimistic person. I can adapt to any kind of environment and learn any new technology given time."
  skills:
    - name: C
      percentage: 75
    - name: C++
      percentage: 90
    - name: Python
      percentage: 85
    - name: CSS
      percentage: 90
    - name: Java
      percentage: 75
    - name: JavaScript
      percentage: 80
    - name: HTML5
      percentage: 90
    - name: Sql
      percentage: 95
  # Experience
  disable_experience: false
  experience:
   - company: "Vignan's Foundations for Science Technology and Research"
     role: "Attended Importance of Cloud Native Product Development"
     startdate: July 2021
     enddate: July 2021
     featuredpoints:
       - point: 
       - point: 

  # Education
  disable_education: false
  education:
    - degree: "B.Tech"
      branch: "Computer Science and Engineering"
      university: "Amrita Vishwa Vidhyapeetham"
      startedyear: "2019"
      graduation: "2023"
    - degree: "12th-HSC"
      branch: "84.6%"
      university: "SBOA Matriculation Higher Secondary School, Madurai"
      startedyear: "2018"
      graduation: "2019"
    - degree: "10th SSLC "
      branch: "91.8%"
      university: "SBOA Matriculation Higher Secondary School, Madurai"
      startedyear: "2016"
      graduation: "2017"

  # Projects
  disable_projects: false
  projects:
    - name: "Random Password Generator"
      img: https://github.com/PaviG26/PaviG26.github.io/raw/source/static/images/download.png
      description: "A successful code that create the password."
    - name: "Covid 19 Vaccination Progress Prediction"
      img: https://github.com/PaviG26/PaviG26.github.io/raw/source/static/images/images.png
      description: "A sucessful code that create the Covid 19 Vaccination Progress Prediction"
    - name: "Customer Segmentation k Means clustering"
      img: https://github.com/PaviG26/PaviG26.github.io/raw/source/static/images/customer.png
      description: "A successful code that create the customer segmentation K means clustering"

  disable_achievements: true
  achievements:
    - title: Phobos
      description: Winners in paper presentation. Presented 
      img: /images/Phobos.jpeg
      
  # Contact
  disable_contact: false
  contact_content: My inbox is constantly open. I'll do my best to respond to you, whether you have a question or simply want to say hello!
  email: "pavig026@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: true

